#  ./mvnw clean package
# ./mvnw spring-boot:run
server:
  address: 0.0.0.0
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: back-end
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DATABASE}

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings
  endpoint:
    health:
      show-details: always

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION_TIME:3600000}
